[build]
  command = "npm run build"
  publish = "dist"

# Handle SPA routing for React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables will be set in the Netlify UI
[build.environment]
  NODE_VERSION = "18"

# Enable CORS headers if needed
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization" 