version: '3.8'

services:
  # Frontend Development
  frontend-dev:
    build:
      context: ./petroleum-front
      target: build
    container_name: petroleum-front-dev
    volumes:
      - ./petroleum-front:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: npm run dev
    networks:
      - petroleum-network

  # Backend Development
  backend-dev:
    build:
      context: ./petroleum-backend
      target: builder
    container_name: petroleum-backend-dev
    volumes:
      - ./petroleum-backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/petroleum
      - REDIS_URI=redis://redis:6379
    command: npm run dev
    depends_on:
      - mongodb
      - redis
    networks:
      - petroleum-network

  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: petroleum-mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - petroleum-network

  # Redis service
  redis:
    image: redis:alpine
    container_name: petroleum-redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - petroleum-network

volumes:
  mongodb_data:
  redis_data:

networks:
  petroleum-network:
    driver: bridge 