version: '3.8'

services:
  # Development backend service
  backend-dev:
    build:
      context: .
      target: builder
    container_name: petroleum-backend-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb+srv://admin:admin@cluster0.pmxg5.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - REDIS_URI=redis://redis:6379
    command: npm run dev
    depends_on:
      - redis
    networks:
      - petroleum-network

  # Production backend service
  backend-prod:
    build: .
    container_name: petroleum-backend-prod
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb+srv://admin:admin@cluster0.pmxg5.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - REDIS_URI=redis://redis:6379
    depends_on:
      - redis
    networks:
      - petroleum-network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  # Redis service
  redis:
    image: redis:alpine
    container_name: petroleum-redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - petroleum-network

volumes:
  redis_data:

networks:
  petroleum-network:
    driver: bridge
